### ISSUE TITLE
Set up GitHub actions to build dpkg, etc.

### ISSUE THREAD

**Issue by larseggert** [L4STeam/iproute2#1]
It would be great if you could set up a GitHub Actions workflow that would build Debian packages, etc. of the kernel for easy experimentation.

(You probably want to do something like this for CI reasons anyway.)

**Comment by oliviertilmans** [comment]
Similarly to the kernel, you now have a stable *.deb at:
https://github.com/L4STeam/iproute2/releases/download/master-build/iproute2-l4s.zip

**Comment by larseggert** [comment]
There is also an `iproute2` deb included with the kernel artifacts, is that sufficient?

**Comment by oliviertilmans** [comment]
This is the same package.
The *.deb included in the zip archive from the linux repo fetches the iproute build from this repo, see
https://github.com/L4STeam/linux/blob/testing/.github/workflows/kernel.yml#L71


[https://avatars0.githubusercontent.com/u/46755634?s=400&v=4]<https://github.com/L4STeam/linux/blob/testing/.github/workflows/kernel.yml#L71>
L4STeam/linux<https://github.com/L4STeam/linux/blob/testing/.github/workflows/kernel.yml#L71>
Kernel tree containing patches for TCP Prague and the dualpi2 qdisc - L4STeam/linux
github.com


________________________________
